### ISSUE TITLE
Library project resources not found

### ISSUE THREAD

**Issue by vekexasia** [blundell/tests-app-robolectric-junit#3]
Hello there,

i'm using your template to test my app. Currently my app structure is
```
 library\
 mobile\
 robolectrictests\
```

The test i'm issuing uses both res from mobile and library projects. I am not able to get robolectric not to trigger ResourceNotFoundException :(

Other tests using res only from one or the other are working fine.

Any hint?

**Comment by blundell** [comment]
You could attempt what is stated here #6 or you could debug your RobolectricTestRunner to see why it doesn't find your resources (i.e. where is it looking)
