### ISSUE TITLE
Error:(13, 0) No signature of method: com.android.build.gradle.AppPlugin.getBootClasspath() is applicable for argument types: () values: []

### ISSUE THREAD

**Issue by codebased** [blundell/tests-app-robolectric-junit#9]
Hi mate,

After downloading the latest test, 

I am getting the following error: 

/Users/codebased/Documents/gits/tests-app-robolectric-junit/robolectric-tests/build.gradle
Error:(13, 0) No signature of method: com.android.build.gradle.AppPlugin.getBootClasspath() is applicable for argument types: () values: []

Can you please be able to advise what I should be doing?

I am on gradle-2.2.1

**Comment by blundell** [comment]
Fixed here: https://github.com/blundell/tests-app-robolectric-junit/commit/6af752bc2eaa5875f7618d0a66a6c67feca46c2b

**Comment by codebased** [comment]
thank you.
